// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type UpdateRequest struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Token    string `json:"token"`
	Password string `json:"password"`
}

type UpdateResponse struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Create_time string `json:"create_time"`
	Update_time string `json:"update_time"`
}

type DeleteRequest struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	Email     string `json:"email"`
	IsDeleted int64  `json:"is_deleted"`
}

type DeleteResponse struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Create_time string `json:"create_time"`
	Update_time string `json:"update_time"`
	IsDeleted   int64  `json:"is_deleted"`
}
